### ISSUE TITLE
第2回準備TODO

### ISSUE THREAD

**Issue by tom-256** [kanazawa-js/community-page#26]
- [x] 日程ぎめ
- [x] 会場ぎめ
- [ ] 会場の鍵の受け取り
- [ ] zoomURLの事前発行（30min x 時間）
- [ ] Chromeにシークレットモードで接続してicloud.comからKeynoteを垂れ流す
- [ ] 付近の駐車場に関する情報をアナウンス（上限有りコインパ）
- [ ] 2回目開催時には3回目のイベント日時を決めておく
- [ ] 近隣駐車場の案内
- [ ] 会場PCのセットアップ
- [ ] 写真共有用のDropbox用意
- [ ] 写真の保存
- [ ] Meetupの写真が必要か登壇者に聞く
- [ ] Conpassに写真撮影がある旨のアナウンスを書く
- [ ] 参加者のLT時間把握
- [ ] 飲食可の懇親タイムの設定
- [ ] エレベーターホールの電気をつける
- [ ] エレベーターホールの電気を消す
- [ ] 案内ボードを出す
- [ ] 案内ボードを片付ける
- [ ] どういうイベントにしたいかブログに書く @yu-kgr

**Comment by yu-kgr** [comment]
[ ] zoomURLの事前発行（30min x 時間）
[ ] Chromeにシークレットモードで接続してicloud.comからKeynoteを垂れ流す

**Comment by yu-kgr** [comment]
- [ ] 付近の駐車場に関する情報をアナウンス（上限有りコインパ）
- [ ] 2回目開催時には3回目のイベント日時を決めておく
- [ ] 懇親会の検討

**Comment by yu-kgr** [comment]
アンケート結果の展開がほしいというお声もあったので、
みんなの要望として、サマリを公開してもよさそう。

**Comment by tom-256** [comment]
TODOのグルーピング必要
- 1ヶ月前
- 2週間前
- 開催直前
- 開催後

**Comment by kentaro-m** [comment]
## 日程
4月25日 (土) 13:00〜17:00

## 会場
Zoom (オンライン)

## TODO
- [ ] Zoonアカウント取得 (ミナカワさん)
- [ ] Zoomの設定変更 (ミナカワさん)
- [ ] Kanazawa.js案内スライド変更 (ミナカワさん)
- [ ] ConnpassでZoomとSlackのURL共有 (1週間前) (マツシタ)
  - 参加者のみに送るようにする
- [ ] ConnpassでZoomとSlackのURL共有 (1日前) (マツシタ)
  - 参加者のみに送るようにする
- [ ] Kanazawa.jsでのTwiiterの開催告知 (1ヶ月前) (モリタ)
- [ ] Kanazawa.jsでのTwiiterの開催告知 (1週間前) (モリタ)
