### ISSUE TITLE
第2回リモート開催準備

### ISSUE THREAD

**Issue by kentaro-m** [kanazawa-js/community-page#29]
## 日程
4月25日 (土) 13:00〜17:00

## 会場
Zoom (オンライン)

## TODO
- [x] Zoonアカウント取得 (ミナカワさん)
- [x] Zoomの設定変更 (ミナカワさん)
- [x] Kanazawa.js案内スライド変更 (ミナカワさん)
- [x] ConnpassでZoomとSlackのURL共有 (1週間前) (マツシタ)
  - 参加者のみに送るようにする
- [x] ConnpassでZoomとSlackのURL共有 (1日前) (マツシタ)
  - 参加者のみに送るようにする
- [x] Kanazawa.jsでのTwiiterの開催告知 (1ヶ月前) (モリタ)
- [x] Kanazawa.jsでのTwiiterの開催告知 (1週間前) (モリタ)

**Comment by yu-kgr** [comment]
zoomの設定変更ってなんでしたっけ？

**Comment by yu-kgr** [comment]
>Zoomの設定変更
パスワードを設定したので、
再開前にメールを送信する際、Zoomの接続URLに合わせてパスワードも送付する。

**Comment by yu-kgr** [comment]
dropboxに#02のスライドを入れました。

**Comment by kentaro-m** [comment]
@yu-kgr @tom-256 
第2回お疲れ様でした！クローズします
