### ISSUE TITLE
kzjs#03の準備

### ISSUE THREAD

**Issue by yu-kgr** [kanazawa-js/community-page#30]
## 日程
5月23日 (土) 13:00〜17:00

## 会場
Zoom (オンライン)

## TODO
- [x] ZoomMTGのスケジュールセット
- [x] 案内スライド変更
- [x] Connpassイベントページの作成
- [ ] [Comment Screenの準備](https://commentscreen.com/)
- [x] Googleフォームでアンケートを作成（任意）
- [ ] ConnpassでZoomとSlackのURL共有（1週間前） 
  - 「参加者のみ」に送信する
- [ ] ConnpassでZoomとSlackのURL共有（1日前）
  - 「参加者のみ」に送信する
- [x] Kanazawa.jsでのTwiiterの開催告知（1ヶ月前）
- [x] Kanazawa.jsでのTwiiterの開催告知（1週間前）
- [x] コミュニティページの更新

**Comment by yu-kgr** [comment]
>ZoomMTGのスケジュールセット
スケジュールを下記のURLでセット済です。
パスワードは各位に直接お知らせします。
https://us02web.zoom.us/j/85764367611

>案内スライド変更
作成したものをDropboxに入れました。

> Connpassイベントページ作成
作成済み => https://kanazawajs.connpass.com/event/175040/

> Googleフォームでアンケートを作成（任意）
作成してスライド内に記載済み。

**Comment by yu-kgr** [comment]
下記対応済み
>Kanazawa.jsでのTwiiterの開催告知（1ヶ月前）
https://twitter.com/knzw_js/status/1258710695664709632

**Comment by yu-kgr** [comment]
>コミュニティページの更新

対応済み  
https://kanazawajs.now.sh/

**Comment by tom-256** [comment]
> Kanazawa.jsでのTwiiterの開催告知（1週間前）

https://twitter.com/knzw_js/status/1262033835555868672?s=20
Done

**Comment by kentaro-m** [comment]
> ConnpassでZoomとSlackのURL共有（1週間前）

完了しました
