### ISSUE TITLE
kzjs#4の準備

### ISSUE THREAD

**Issue by tom-256** [kanazawa-js/community-page#33]
## 会場
Spatial (オンライン)

## TODO
- [x] Spatial Chatのセット
- [x] 案内スライド変更
- [x] Connpassイベントページの作成
- [x] Googleフォームでアンケートを作成（任意）
- [x] ConnpassでSpatial ChatとSlackのURL共有（1週間前） 
  - 「参加者のみ」に送信する
- [x] ConnpassでSpatial ChatとSlackのURL共有（1日前）
  - 「参加者のみ」に送信する
- [x] Kanazawa.jsでのTwiiter / Slack#generalの開催告知（1ヶ月前）
- [x] Kanazawa.jsでのTwiiter / Slack#generalの開催告知（1週間前）
- [x] コミュニティページの更新
- [ ] Next.jsのチュートリアル準備

**Comment by tom-256** [comment]
# 次回テーマ
Next.jsもくもく会

- やりたいことある人は各自Next.jsのもくもくをする
- 決まってない人はNext.jsのチュートリアルをやる

**Comment by yu-kgr** [comment]
>Connpassイベントページの作成

公開した！
https://kanazawajs.connpass.com/event/178678/

**Comment by yu-kgr** [comment]
>コミュニティページの更新

自動化したので次回以降不要
https://github.com/kanazawa-js/community-page/pull/34

**Comment by yu-kgr** [comment]
>Kanazawa.jsでのTwiiterの開催告知（1ヶ月前）

投稿忘れてたので対応しました。
https://twitter.com/knzw_js/status/1272783579437608963

**Comment by yu-kgr** [comment]
> 案内スライド変更
>Googleフォームでアンケートを作成（任意）

こちら対応済み

**Comment by yu-kgr** [comment]
>Spatial Chatのセット
https://spatial.chat/s/いつもの

**Comment by yu-kgr** [comment]
>ConnpassでSpatial ChatとSlackのURL共有（1週間前）
>「参加者のみ」に送信する

送信済み

**Comment by yu-kgr** [comment]
>Kanazawa.jsでのTwiiterの開催告知（1週間前）

https://twitter.com/knzw_js/status/1274907708504694785

**Comment by yu-kgr** [comment]
完了しているのでクローズします
